import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import { ThemeProvider } from "./providers/theme-provider";

import { ReactQueryClientProvider } from "./providers/ReactQueryClientProvider";

import "./globals.css";

const archivo = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={archivo.className}>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
          </ThemeProvider>
        </body>
      </UserProvider>
    </html>
  );
}
